export const MESSAGE_LIST = 'MESSAGE_LIST';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SAVE_ACCESS_TOKEN = 'SAVE_ACCESS_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SINGLE_MESSAGE = 'SINGLE_MESSAGE';
export const FORWARD_MESSAGE = 'FORWARD_MESSAGE';
export const CREATE_NUMBER = 'CREATE_NUMBER';
export const NUMBER_LIST = 'NUMBER_LIST';
export const CALLBACK_URL = 'CALLBACK_URL';
export const CLEAR_FAILED_STATUS = 'CLEAR_FAILED_STATUS';
export const SIGNIN = 'SIGNIN';
export const SIGNUP = 'SIGNUP';
export const DELETE_NUMBER = 'DELETE_NUMBER';
export const CONTACT_LIST = 'CONTACT_LIST';
export const SIGNLE_CHAT_HISTORY = 'SIGNLE_CHAT_HISTORY';
export const CREATE_EXTERNAL_NUMBER = 'CREATE_EXTERNAL_NUMBER';
export const ROUTE_LIST = 'ROUTE_LIST';

